Flickrtype flickr/design/standard/templates/class/datatype/edit/flickrtype

ContentClass_flickrtype_flickr_target_select_{$class_attribute.id}
ContentClass_flickrtype_flickr_target_id_{$class_attribute.id}